name: Delete Specific Branch After Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'update-cookbook-submodule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUBLIC_DOCS_WRITE_TOKEN }}
          submodules: true
      - name: Delete Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push origin --delete ${{ github.event.pull_request.head.ref }}
